name: Release Artifacts

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docker/**'
    branches:
      - main

jobs:
  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: |
          pip install wheel
          pip install twine
          pip install -r requirements.txt
      - name: Compile Linux wheel
        run: |
          python setup.py sdist bdist_wheel
      - name: Get Version
        run: echo "version=$(python wol_api/providers/version.py)" >>$GITHUB_OUTPUT
        id: version
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*.whl"
          artifactErrorsFailBuild: true
          bodyFile: ".github/Changelog.md"
          tag: v.${{ steps.version.outputs.version }}
      - name: Upload to PyPI
        run: |
          python -m twine upload ./dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      - name: Trigger Docker Image build
        run: |
          curl -XPOST -u "${{ secrets.CR_USER }}:${{secrets.CR_PAT}}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/rix1337/WakeOnLAN-API/actions/workflows/BuildImage.yml/dispatches --data '{"ref": "main", "inputs": {"version": "${{ steps.version.outputs.version }}"}"}'
